Update patch set 3
Patch Set 3: Code-Review-1

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 3:
> > > 
> > > image: morganrol/testsuite:test
> > > 
> > > seemed to pull a container but the container does not have the demo repo ?
> > 
> > ==============================================================================
> > Health Distribution Test                                              | FAIL |
> > IOError: [Errno 2] No such file or directory: u'./demo/service_mapping/vFW/service_mapping.json'
> 
> Did you rebuild the docker after patch set 3 ?

hum in theory yes..
I just gave a try docker run -it morganrol/testsuite:test bash
and demo is missing...
hmm

Patch-set: 3
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1